version = 1

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/rajput-hemant/leetcode"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"